version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenish/hello-dropwizard
    container_name: app
    ports:
      - "8080"
